site_name: eraXplor - Cost Export Tool
site_url: https://mohamed-eleraki.github.io/eraXplor
site_description: A Python CLI tool for exporting cost reports over Multi-providers AWS/Azure.
copyright: Copyright &copy; 2025 Mohamed eraki

repo_url: https://github.com/Mohamed-Eleraki/eraXplor
edit_uri: edit/main/docs/
repo_name: Mohamed-Eleraki/eraXplor

theme:
  name: "material"
  palette:
    primary: green
    accent: light green
  features:
    - navigation.sections
    - navigation.sidebar
    - search.suggest
    - search.highlight
    - header.autohide

# fetch date from docstring
plugins:
  - mkdocstrings # must install mkdocstrings first
  - mermaid2
  - search
  - autorefs

markdown_extensions:
  - admonition
  - pymdownx.details

nav:
  # - Welcome to eraXplor - AWS cost Export Toold Docs: index.md
  - Welcome to eraXplor: index.md
  - API Documentation:
      - AWS API: api/aws.md
      - Azure API: api/azure.md
  - AWS (eraXplor-aws):
      - Overview: aws/index.md
      - Tutorials: aws/tutorials.md
      - How-to Guides: aws/how-to-guides.md
      - Explanation: aws/explanation.md
      - Reference: aws/reference.md
  - Azure (eraXplor-azure):
      - Overview: azure/index.md
      - Tutorials: azure/tutorials.md
      - How-to Guides: azure/how-to-guides.md
      - Explanation: azure/explanation.md
      - Reference: azure/reference.md
