site_name: eraXplor - Cost Export Tool

theme:
  name: "material"

# fetch date from docstring
plugins:
  - mkdocstrings # must install mkdocstrings first
  - mermaid2
  - search

markdown_extensions:
  - admonition
  - pymdownx.details

nav:
  # - Welcome to eraXplor - AWS cost Export Toold Docs: index.md
  - Welcome to eraXplor: index.md
  - AWS (eraXplor):
      - Overview: aws/index.md
      - Tutorials: aws/tutorials.md
      - How-to Guides: aws/how-to-guides.md
      - Concepts: aws/explanation.md
  - Azure (eraXplor_az):
      - Overview: azure/index.md
      - Tutorials: azure/tutorials.md
      - How-to Guides: azure/how-to-guides.md
      - Concepts: azure/explanation.md
  - Reference: reference.md
